Use generated keywords file from VSCode extension
ovh/ovh-warp10-datasource pull request #55
Opened 2019-12-31 13:48 UTC by pi-r-p

`monarch.ts` is generated by our documentation server and could be updated easily, by anyone who can copy paste it from [VSCode extension sources](https://github.com/senx/VSCode-WarpScriptLanguage/blob/master/monarch.ts).

I will try to keep it up to date with each Warp 10 release.

2019-12-31 13:48 UTC, claassistantio commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ovh/ovh-warp10-datasource?pullRequest=55) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ovh/ovh-warp10-datasource?pullRequest=55) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ovh/ovh-warp10-datasource?pullRequest=55) it.</sub>

2020-01-02 16:57 UTC, aurrelhebert approved these changes

2020-01-03 14:06 UTC, redref requested changes
@pi-r-p : Can you push compiled version (dist folder) alongside this change.

Tested and works pretty well.

Thanks.

2020-01-03 14:48 UTC, miton18 submitted a review, later dismissed
As said by @redref, you also need to push the builded files (/dist)

2020-01-03 21:17 UTC, pi-r-p commented
transpilation commited

2020-01-06 11:04 UTC, redref approved these changes

2020-01-06 11:05 UTC, merged