Console output of the full query, with headers
ovh/ovh-warp10-datasource pull request #56
Opened 2019-12-31 15:24 UTC by pi-r-p

Just changed the console output for a better understanding of WarpScript substitutions.

For example, multiple selection on a variable are translated in a string separated by `+` in WarpScript:
![image](https://user-images.githubusercontent.com/37228740/71625738-b3139200-2be9-11ea-8175-b02a245e4e78.png)

This is not obvious...

2020-01-02 16:57 UTC, aurrelhebert approved these changes

2020-01-02 18:51 UTC, redref approved these changes

2020-01-03 14:05 UTC, redref requested changes
@pi-r-p : Can you push compiled version (dist folder) alongside this change.

Thanks.

2020-01-03 14:51 UTC, miton18 requested changes
You also need to push builded files `/dist`

2020-01-03 21:11 UTC, pi-r-p commented
dist/ pushed. 
little differences in .d.ts files, can't figure out why.

2020-01-03 22:00 UTC, redref commented
Strange, I cannot reproduce either with node docker image with version 10/12/13.
Maybe build instructions, I use
```
npm install
npm run-script build
```

It would be better to keep only one version of those files (even if it should work as it is). Will document the building process after that :wink:

2020-01-03 22:17 UTC, pi-r-p commented
I used npm install and yarn build after a git reset of dist/ 
Maybe little differences in the npm package version used.
Anyway, it should work.

2020-01-06 11:01 UTC, redref approved these changes

2020-01-06 11:02 UTC, merged