fix #57: multi value better handling
ovh/ovh-warp10-datasource pull request #58
Opened 2020-01-03 11:02 UTC by redref

Working on #57 .
Tried to cover standard cases. Runned some tests, but they are not exhaustive.

2020-01-03 11:03 UTC, redref commented
@tduboys : if you can try it and confirm, would be awesome !

2020-01-03 14:34 UTC, tduboys commented
HI,
I confirm it works.
The patch creates a new variable called « <variable>_list » that contains all selected options on a list format
and a second variable <variable> with the REOPTALT option to be used on FETCH.

I only tested on a FETCH filter, but it's working on this case.
Thanks @redref

2020-01-03 15:03 UTC, miton18 requested changes

2020-01-03 15:03 UTC, miton18 commented on src/warp10-datasource.ts
> +      if (myVar.current.value != null) {
We can enhance it with:
```js
if (myVar.current.value == null) {
    continue
}
```

2020-01-03 15:03 UTC, miton18 commented on src/warp10-datasource.ts
> +        if (myVar.current.value === '$__all' || (myVar.current.value.length === 1 && myVar.current.value[0] === '$__all')) {
I think `myVar.current.value.length === 1` can have a weird behaviour depending of current value type (string or array)

2020-01-03 15:03 UTC, miton18 commented on src/warp10-datasource.ts
> +          value_l = "[ ".concat(myVar.options.slice(1).map(e => "'" + e.value + "'").join(" "), " ]");
```js
 value_l = `[ ${ myVar.options.slice(1).map(e => `'${ e.value }'`).join(" ") } ]`;
```

2020-01-03 15:03 UTC, miton18 commented on src/warp10-datasource.ts
> +            value = "'" + myVar.allValue + "'";
value = `'${ myVar.allValue }'`;

2020-01-03 15:22 UTC, redref commented on src/warp10-datasource.ts
> +      if (myVar.current.value != null) {
This is a behavior change.
Nevertheless, I think we can do it safely as grafana will provide value no matter what.

2020-01-03 23:35 UTC, pi-r-p commented
@redref : Sorry, I worked on the same subject yesterday night and tonight... And I just discovered you also did a PR for the same issue. 
We may discuss it on monday maybe ?

2020-01-06 09:18 UTC, redref commented
@pi-r-p : Closing this, despite my concerns on your PR, it is better styled and cover a bit more.

2020-01-06 09:18 UTC, closed without merging