hotfix: $__all when multi not checked
ovh/ovh-warp10-datasource pull request #62
Opened 2020-01-09 14:27 UTC by redref

2020-01-10 08:29 UTC, pi-r-p commented
Is it a corner case where user enters $__all manually ?
Nice.

2020-01-10 09:01 UTC, redref commented
Nope, when multi is not ticked, the value is not an array.

2020-01-13 10:48 UTC, miton18 requested changes

2020-01-13 10:48 UTC, miton18 commented on src/warp10-datasource.ts
> +      if (((Array.isArray(value) && (value.length == 1 && value[0] === '$__all')) || value == "$__all")) {
`value === "$__all"`

2020-01-13 13:40 UTC, miton18 approved these changes

2020-01-13 13:50 UTC, aurrelhebert approved these changes

2020-01-13 13:52 UTC, merged